# Site wide configuration
# Site wide configuration
source                   : .tmp/src
destination              : .tmp/dist

title                    : "Salla Eliisa Toikkanen"
description              : "Personal website of mine!"
logo                     : #/assets/images/site-logo.png
teaser                   : #/assets/images/default-teaser.png
locale                   : "en_US"
words_per_minute         : 200
title_separator          : "×"

repository               : ##
url                      : "https://stoikkanen.github.io/"

twitter:
  username               : ##

social:
  name                   : "Salla Eliisa Toikkanen"
  links:
   # - ""
    
# Site owner
author:
  name                   : "Salla Toikkanen"
  url                    : "https://stoikkanen.github.io/"
  bio                    : "memememem"
  picture                : "neiti_toikkanen.png"
  
